DroneCone/Account/urls.py
from django.urls import path

from .views import *
from . import views

app_name = "account"
urlpatterns = [
    path("signup/", views.RegisterView, name='signup'),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),

    path("change-password/", PasswordChangeView.as_view(), name='password_change'),
    path("change-password/done/", PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path("profile/", view=ProfileView.as_view(), name="profile"),

    path('drone-owner-creation/', views.DroneOwnerRegisterView, name='drone_owner_creation')

]

DroneCone/DroneCone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("DroneCustomer.urls"), name="drone_cone"),
    path("admin/", admin.site.urls),
    path("droneadmin/", include("DroneAdmin.urls")),
    path("account/", include("Account.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

DroneCone/DroneCustomer/urls.py
from django.urls import path

from . import views
from .views import *


urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    path("checkout/", views.checkout, name="checkout"),
    path("account/", views.account, name="account"),
    path("edit_account/", views.editAccount, name="editaccount"),
    path('update-account/', views.update_account, name='update_account'),
    path('create_icecreamcone/', IceCreamConeCreateView.as_view(), name='create_icecreamcone'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add_to_cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('order_history/', OrderListView.as_view(), name='order_history'),
    path('get_user_id/', GetUserIdView.as_view(), name='get_user_id'),
    path("manage-drones/", views.droneManagement, name="my_drones"),
    # Remove ?
    path("manage-my-drone/", views.manageMyDrone, name="manage_my_drone"),
    path('manage-my-drone/create/', views.customerCreateDrone, name='customer_create_drone'),
    path('manage-my-drone/<int:drone_id>/update', views.customerEditDrone, name='customer_edit_drone'),
    path('manage-my-drone/<int:drone_id>/delete', views.customerDeleteDrone, name='customer_delete_drone'),
    #
    # path("edit-account/", views.editAccount, name="edit_account"),
    path('menu-items/', MenuItemsAPI.as_view(), name='menu_items_api'),
    path('topping-items/', ToppingsItemsAPI.as_view(), name='topping_items_api'),
    path('cone-items/', ConeItemsAPI.as_view(), name='cone_items_api'),
    path('orders/', OrderCreateView.as_view(), name='order_create'),
    path('submit_order/', views.submit_order, name='submit_order'),
    path('update_order_status/<int:order_id>/', UpdateOrderStatusView.as_view(), name='update_order_status'),
    path('delete_order/<int:order_id>/', delete_order, name='delete_order'),
]

DroneCone/Account/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', primary_key=True)
    phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=255, blank=True)
    drone_owner = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"

DroneCone/DroneCustomer/models.py
from django.contrib.auth.models import User
from django.db import models
from decimal import Decimal


class Markup(models.Model):
    markup_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('10.0'))

    @classmethod
    def get_instance(cls):
        instance, created = cls.objects.get_or_create(pk=1)
        return instance

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.markup_percentage}%"


class Drone(models.Model):
    SIZE_CHOICES = [
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="drone")
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=10, choices=SIZE_CHOICES, default='small')

    drone_weight_g = models.PositiveIntegerField()
    battery_capacity_mAh = models.PositiveIntegerField()
    battery_voltage = models.DecimalField(max_digits=5, decimal_places=2)
    battery_level = models.DecimalField(max_digits=3, decimal_places=2)  # 1.0 - 0.0
    hours_worked = models.DecimalField(max_digits=4, decimal_places=1, default=Decimal('0.0'))
    dollar_revenue = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0.00'))

    enabled = models.BooleanField(default=True)
    in_flight = models.BooleanField(default=False)

    def is_available(self):
        return self.enabled and not self.in_flight

    def get_drone_status(self):
        if self.enabled:
            return "Available" if not self.in_flight else "In Flight"
        return "Disabled"

    def __str__(self):
        return f"{self.name}"


class IceCream(models.Model):
    flavor = models.CharField(max_length=127)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    qty = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Ice cream"

    def __str__(self):
        return f"{self.flavor}"


class Topping(models.Model):
    name = models.CharField(max_length=127)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    qty = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"


class Cone(models.Model):
    name = models.CharField(max_length=127)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    qty = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"


class IceCreamCone(models.Model):
    SIZE_CHOICES = [
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
    ]
    size = models.CharField(max_length=10, choices=SIZE_CHOICES, default='small')
    flavor = models.ForeignKey('IceCream', on_delete=models.CASCADE)
    toppings = models.ManyToManyField('Topping', blank=True)
    cone = models.ForeignKey('Cone', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.flavor} | {self.cone} | {self.size} | {[str(topping) for topping in list(self.toppings.all())]}"

    def get_cone_info(self):
        return {'size': str(self.size),
                'flavor': str(self.flavor),
                'toppings': [str(topping) for topping in list(self.toppings.all())],
                'cone': str(self.cone),
                'price': str(self.get_price())}

    def get_price(self):
        price = self.cone.price + sum(topping.price for topping in self.toppings.all())
        match self.size:
            case 'small':
                price += self.flavor.price * 1
            case 'medium':
                price += self.flavor.price * 2
            case 'large':
                price += self.flavor.price * 3
        return price


class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('preparing', 'Preparing'),
        ('delivering', 'Delivering'),
        ('delivered', 'Delivered'),
        ('canceled', 'Canceled'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    drone = models.ForeignKey(Drone, on_delete=models.SET_NULL, blank=True, null=True)
    cones = models.JSONField()
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order #{self.pk} - {self.status}"

    def get_order_total(self):
        total_price = Decimal('0.00')
        cone_data_list = self.cones if isinstance(self.cones, list) else [self.cones]

        for cone_data in cone_data_list:
            cone_price = Decimal(cone_data.get('price', '0.00'))
            total_price += cone_price

        return total_price

    def get_cone_info(self):
        # Check if `self.cones` is a list of dictionaries (JSON data)
        if isinstance(self.cones, list):
            return self.cones
        # If `self.cones` is a single dictionary, return it inside a list
        elif isinstance(self.cones, dict):
            return [self.cones]
        # If `self.cones` is neither, return an empty list
        else:
            return []

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cart')
    cones = models.ManyToManyField('IceCreamCone', blank=True)

    def remove_all_cones(self):
        self.cones.clear()

    def get_cones_info(self):
        return [cone.cone_to_json() for cone in self.cones.all()]

    def __str__(self):
        return f"{self.user.username}'s cart"

DroneCone/Account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import EmailField, ModelForm, TextInput
from .models import Profile
from django import forms




class CustomUserCreationForm(UserCreationForm):
    email = EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'custom-email-input border border-gray-400 rounded'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ("email",)
        widgets = {
            'username': TextInput(attrs={'class': 'custom-username-input border border-gray-400 rounded'}),
            'password1': forms.PasswordInput(attrs={'class': 'custom-password1-input border border-gray-400 rounded'}),
            'password2': forms.PasswordInput(attrs={'class': 'custom-password2-input border border-gray-400 rounded'}),
        }

        

class CustomUserForm(ModelForm):
    email = EmailField(required=True)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('address', 'phone', 'drone_owner')

DroneCone/DroneCustomer/forms.py
from django import forms
from DroneCustomer.models import Drone
from decimal import Decimal



class DroneForm(forms.ModelForm):
    battery_percentage = forms.DecimalField(decimal_places=0, min_value=0, max_value=100)

    class Meta:
        model = Drone
        fields = [
            'name',
            'size',
            'drone_weight_g',
            'battery_capacity_mAh',
            'battery_voltage',
            'battery_percentage',
            'enabled',
            ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.battery_level is not None:
            initial_battery_percentage = (Decimal(self.instance.battery_level) * Decimal(100))
            self.initial['battery_percentage'] = initial_battery_percentage.quantize(Decimal(1))

    def save(self, commit=True, kwargs=None):
        model = super(forms.ModelForm, self).save(commit=False)

        battery_percentage = self.cleaned_data.get('battery_percentage')
        model.battery_level = battery_percentage / Decimal(100)

        if commit:
            model.save()
        return model

DroneCone/Account/views.py
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic import CreateView
from .forms import CustomUserCreationForm, CustomUserForm
from django.contrib.auth import login
from DroneAdmin.forms import ProfileForm
from django.contrib.auth.decorators import user_passes_test


def RegisterView(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()  # Save the User instance
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user) 
            return redirect('home')
    else:
        user_form = CustomUserCreationForm()
        profile_form = ProfileForm()
        profile_form.drone_owner = False

    return render(request, 'Account/register.html', {'user_form': user_form, 'profile_form': profile_form})


def DroneOwnerRegisterView(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()  # Save the User instance
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user) 
            return redirect('manage_my_drone')
    else:
        initial_data = {'drone_owner': True}

        # Create an instance of the ProfileForm with the initial data
        profile_form = ProfileForm(initial=initial_data)
        user_form = CustomUserCreationForm()

    return render(request, 'DroneCustomer/droneOwnerCreation.html', {'user_form': user_form, 'profile_form': profile_form})


class LoginView(auth_views.LoginView):
    template_name = 'account/login.html'


class LogoutView(auth_views.LogoutView):
    template_name = "account/logout.html"
    http_method_names = ["get", "post", "options"]

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Logout may be done via POST."""
        auth_logout(request)
        messages.success(request, 'Successfully logged out.')
        redirect_to = self.get_success_url()
        if redirect_to != request.get_full_path():
            # Redirect to target page once the session has been cleared.
            return HttpResponseRedirect(redirect_to)
        return super().get(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    get = get  # Django4.2 has get = post, but we don't want the user to logout on get request.


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'account/password_change.html'
    success_url = reverse_lazy("account:password_change_done")


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'account/password_change_done.html'


class PasswordResetView(SuccessMessageMixin, auth_views.PasswordResetView):
    template_name = 'account/password_reset.html'
    email_template_name = 'account/password_reset_email.html'
    subject_template_name = 'account/password_reset_subject.txt'
    success_message = ("Please check your email for the password reset instructions. "
                       "You will only receive an email if an account is associated with the provided email.")
    success_url = reverse_lazy('account:password_reset_done')


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'account/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'account/password_reset_from_key.html'
    success_url = reverse_lazy("account:password_reset_complete")


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'account/password_reset_from_key_done.html'


# class ProfileView(LoginRequiredMixin, View):
#     template_name = 'account/user_profile.html'
#     user_form_class = CustomUserForm
#     profile_form_class = ProfileForm

#     def get(self, request, *args, **kwargs):
#         user_form = self.user_form_class(instance=request.user)
#         profile_form = self.profile_form_class(instance=request.user.profile)
#         return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})

#     def post(self, request, *args, **kwargs):
#         user_form = self.user_form_class(request.POST, instance=request.user)
#         profile_form = self.profile_form_class(request.POST, instance=request.user.profile)

#         if user_form.is_valid() and profile_form.is_valid():
#             user_form.save()
#             profile_form.save()
#             messages.success(request, 'Your profile is updated successfully')
#             return redirect('account:profile')

#         return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})

DroneCone/DroneCustomer/templates/DroneCustomer/customer_add_drone.html
{% extends 'DroneCustomer/base.html' %}
<!--- Comment -->
{% block content %}
    <div class="bg-white p-4 shadow rounded-lg">
        <form method="POST">
            {% csrf_token %}

            {% if form.errors %}
                <ul class="text-red-500">
                    {% for error in form.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <table class="table-auto w-full">
                <tr>
                    <td class="font-semibold text-gray-700">Owner:</td>
                    <td>{{ form.owner }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Name:</td>
                    <td>{{ form.name }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Size:</td>
                    <td>{{ form.size }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Weight:</td>
                    <td>
                        {{ form.drone_weight_g }}
                        <small class="text-gray-500">g</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Battery Capacity:</td>
                    <td>
                        {{ form.battery_capacity_mAh }}
                        <small class="text-gray-500">mAh</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Battery Voltage:</td>
                    <td>
                        {{ form.battery_voltage }}
                        <small class="text-gray-500">v</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Battery Level:</td>
                    <td>
                        {{ form.battery_level }}
                        <small class="text-gray-500">% (Must be a decimal between 1.0 and 0.0)</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Drone is Enabled:</td>
                    <td>{{ form.enabled }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Drone is in-flight:</td>
                    <td>{{ form.in_flight }}</td>
                </tr>
     
            </table>

            <div class="mt-4 flex items-center">
                <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded-md">Save</button>
                <a href="{% url 'manageMyDrone' %}" class="ml-2 text-gray-500">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

DroneCone/DroneCustomer/templates/DroneCustomer/customer_delete_drone.html
{% extends 'base.html' %}


{% block inner %}
    <div class="flex justify-center">
        <div class="relative max-w-fit bg-white rounded-xl overflow-hidden p-4 m-4">
            <p class="text-center text-bold text-xl">Are you sure you want to delete this drone?</p>
            <form method="post" class="mt-4 flex justify-end">
                {% csrf_token %}
                <a href="{% url 'manage_my_drone' %}" class="text-blue-500 px-4 py-2 rounded-md transition ease-in-out duration-100 hover:scale-105 hover:bg-gray-100">Cancel</a>
                <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md ml-2 transition ease-in-out duration-100 hover:scale-105 hover:bg-red-600">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

DroneCone/DroneCustomer/templates/DroneCustomer/delete_confirmation.html
<!-- delete_confirmation.html -->
<div class="modal">
    <div class="modal-content">
        <p>Are you sure you want to delete this drone?</p>
        <button id="confirmDelete">Yes</button>
        <button id="cancelDelete">Cancel</button>
    </div>
</div>

<script>
    document.getElementById('confirmDelete').addEventListener('click', function () {
        // Redirect to the delete URL or perform the delete action here
        window.location.href = '{% url "delete_drone" drone.id %}';
    });

    document.getElementById('cancelDelete').addEventListener('click', function () {
        // Close the modal or perform any other action
        document.querySelector('.modal').style.display = 'none';
    });
</script>

DroneCone/DroneCustomer/templates/DroneCustomer/droneOwnerCreation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Drone Cones</title>
</head>

<body class="min-h-screen flex items-center justify-center"
    style="background-image: url('{% static 'images/Icecreambackground.png' %}'); background-size: cover; background-repeat: no-repeat;">

    <div class="container">
        <div class="card">
            <h1 class="text-4xl mb-4 font-bold" style="color: #CDB4DB; text-align: center;">Drone Owner Sign Up</h1>
            <p style="text-align: center;">
                Already have an account? Click here to <a href="{% url 'account:login' %}"><strong>Log in</strong></a>.
            </p>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    min-height: 100vh;
                    background-color: #f0f0f0;
                }

                .card {
                    background-color: #fff;
                    padding: 8px;
                    padding-left: 30px;
                    padding-right: 30px;
                    border-radius: 8px;
                    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                    text-align: center;
                }

                .inputLabel {
                    font-family: Verdana, Geneva, Tahoma, sans-serif;
                    font-weight: lighter;
                    color: #210631;
                    font-size: 14px;
                    text-align: left;
                }

                .required {
                    color: red;
                }

                .button-link {
                    display: inline-block;
                    border: none;
                    background-color: white;
                    color: #000000;
                    /* Change this to your desired text color */


                }
            </style>
            <div id="powered-by" style="position: absolute;
                        top: 13px;
                        right: 10px;
                        font-size: 17px;
                        font-family: Arial;
                        color: #626262;">Powered by <strong>Dorsal Froat Doom</strong>
            </div>

            <form class="signup" id="signup_form" method="post" action="{% url 'account:drone_owner_creation' %}">
                {% csrf_token %}
                <table class="table-auto w-full">
                    <tr>
                        <td class="inputLabel"><span class="required">*</span>Username:</td>
                        <td>{{ user_form.username }}</td>
                    </tr>
                    <tr>
                        <td class="inputLabel"><span class="required">*</span>Password:</td>
                        <td>{{ user_form.password1 }}</td>
                    </tr>
                    <tr>
                        <td class="inputLabel"><span class="required">*</span>Confirm Password:</td>
                        <td>{{ user_form.password2 }}</td>
                    </tr>
                    <tr>
                        <td class="inputLabel"><span class="required">*</span>Email:</td>
                        <td>{{ user_form.email }}</td>
                    </tr>

                    <tr>
                        <td class="inputLabel">Phone:</td>
                        <td>{{ profile_form.phone }}</td>
                    </tr>
                    <tr>
                        <td class="inputLabel">Address:</td>
                        <td>{{ profile_form.address }}</td>
                    </tr>
                    <tr>
                        <td class="inputLabel">Drone Owner:</td>
                        <td style="text-align:left;">{{ profile_form.drone_owner }}</td>
                    </tr>
                </table>
                {% if user_form.errors %}
                <div class="error-box"
                    style="background-color: #FFBABA; color: #D8000C; padding: 10px; margin-top: 15px;">
                    {% for field, errors in user_form.errors.items %}
                    {% for error in errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                    {% endfor %}
                </div>
                {% endif %}

                <button class="button-link" style="cursor: pointer; padding-top:8px" type="submit"><strong>Sign Up
                        »</strong></button>
            </form>
            <p>Click to <a href="{% url 'account:signup' %}"><strong>Register as Customer</strong></a></p>
        </div>
    </div>

</body>

</html>

DroneCone/DroneCustomer/templates/DroneCustomer/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Drone Cones</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" rel="stylesheet">
</head>
<body class="min-h-screen flex items-center justify-center" style="background-image: url('{% static 'images/Icecreambackground.png' %}'); background-size: cover; background-repeat: no-repeat;">

    <div class="bg-white p-6 rounded-lg shadow-lg text-center">
        <h1 class="text-4xl mb-4 font-bold" style="color: #CDB4DB;">Welcome to Drone Cones</h1>
        <div class="text-white font-bold py-2 px-4 rounded-full mb-2" style="background-color: #FFC8DD; transition: background-color 0.3s;"><a href="{% url 'account:login' %}">Log In</a></div><br>
        <div class="text-white font-bold py-2 px-4 rounded-full" style="background-color: #FFAFCC; transition: background-color 0.3s;"><a href="{% url 'account:signup' %}">Sign Up</a></div>
    
        <div id="powered-by" style="position: absolute;
        top: 10px;
        right: 10px;
        font-size: 17px;
        font-family: Arial;
        color: #626262;">Powered by <strong>Dorsal Froat Doom</strong>
        </div>
    </div>

</body>
</html>

DroneCone/DroneCustomer/templates/DroneCustomer/topBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>
        {% block head_title %}
        {% endblock head_title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- CSS files -->
    {% block css %}
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
              integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"/>

    {% endblock css %}
    <!-- Javascript Files -->
    {% block javascript %}
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
                integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
                crossorigin="anonymous"
                referrerpolicy="no-referrer"></script>

    {% endblock javascript %}
</head>

<body>
<div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">DroneCones</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account' %}">My Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:logout' %}">Log Out</a>
                        </li>
                        {% if request.user.is_staff or request.user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'order_history' %}">Admin</a>
                            </li>
                        {% endif %}
                        {% if request.user.profile.drone_owner %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'manage_my_drone' %}">Manage My Drones</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item">
                            <a id="sign-up-link" class="nav-link" href="{% url 'account:signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a id="log-in-link" class="nav-link" href="{% url 'account:login' %}">Log In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
</body>
</html>