DroneCone/Account/urls.py
from django.urls import path

from .views import *
from . import views

app_name = "account"
urlpatterns = [
    path("signup/", views.RegisterView, name='signup'),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),

    path("change-password/", PasswordChangeView.as_view(), name='password_change'),
    path("change-password/done/", PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('reset-password/', PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path("profile/", view=ProfileView.as_view(), name="profile"),

    path('drone-owner-creation/', views.DroneOwnerRegisterView, name='drone_owner_creation')

]

DroneCone/DroneAdmin/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='order_history'),
    path('drone_management/', views.drone_management, name="drone_management"),
    path('drone_management/add_drone/', views.add_drone, name='add_drone'),
    path('drone_management/add_drone/<int:item_id>/', views.add_drone, name='add_drone'),
    path('drone_management/delete_drone/<int:item_id>/', views.delete_drone, name='delete_drone'),
    path('inventory/', views.inventory, name="inventory"),
    path('inventory/add_icecream/', views.add_ice_cream, name='add_ice_cream'),
    path('inventory/add_ice_cream/<int:item_id>/', views.add_ice_cream, name='add_ice_cream'),
    path('inventory/delete_ice_cream/<int:item_id>/', views.delete_ice_cream, name='delete_ice_cream'),
    path('inventory/add_cone/', views.add_cone, name='add_cone'),
    path('inventory/add_cone/<int:item_id>/', views.add_cone, name='add_cone'),
    path('inventory/delete_cone/<int:item_id>/', views.delete_cone, name='delete_cone'),
    path('inventory/add_topping/', views.add_topping, name='add_topping'),
    path('inventory/add_topping/<int:item_id>/', views.add_topping, name='add_topping'),
    path('inventory/delete_topping/<int:item_id>/', views.delete_topping, name='delete_topping'),
    path('sales/', views.sales, name="sales"),
    path('sales/edit_markup/', views.edit_markup, name='edit_markup'),
    path('user_management/', views.user_management, name='user_management'),
    path('user_management/edit_user/<int:user_id>/', views.edit_user, name="edit_user"),
    path('user_management/delete_user/<int:user_id>/', views.delete_user, name="delete_user")
]

DroneCone/DroneCone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("DroneCustomer.urls"), name="drone_cone"),
    path("admin/", admin.site.urls),
    path("droneadmin/", include("DroneAdmin.urls")),
    path("account/", include("Account.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

DroneCone/DroneAdmin/models.py
from django.db import models

# Create your models here.

DroneCone/DroneCustomer/models.py
from django.contrib.auth.models import User
from django.db import models
from decimal import Decimal


class Markup(models.Model):
    markup_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal('10.0'))

    @classmethod
    def get_instance(cls):
        instance, created = cls.objects.get_or_create(pk=1)
        return instance

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.markup_percentage}%"


class Drone(models.Model):
    SIZE_CHOICES = [
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="drone")
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=10, choices=SIZE_CHOICES, default='small')

    drone_weight_g = models.PositiveIntegerField()
    battery_capacity_mAh = models.PositiveIntegerField()
    battery_voltage = models.DecimalField(max_digits=5, decimal_places=2)
    battery_level = models.DecimalField(max_digits=3, decimal_places=2)  # 1.0 - 0.0
    hours_worked = models.DecimalField(max_digits=4, decimal_places=1, default=Decimal('0.0'))
    dollar_revenue = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0.00'))

    enabled = models.BooleanField(default=True)
    in_flight = models.BooleanField(default=False)

    def is_available(self):
        return self.enabled and not self.in_flight

    def get_drone_status(self):
        if self.enabled:
            return "Available" if not self.in_flight else "In Flight"
        return "Disabled"

    def __str__(self):
        return f"{self.name}"


class IceCream(models.Model):
    flavor = models.CharField(max_length=127)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    qty = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Ice cream"

    def __str__(self):
        return f"{self.flavor}"


class Topping(models.Model):
    name = models.CharField(max_length=127)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    qty = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"


class Cone(models.Model):
    name = models.CharField(max_length=127)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    qty = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"


class IceCreamCone(models.Model):
    SIZE_CHOICES = [
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
    ]
    size = models.CharField(max_length=10, choices=SIZE_CHOICES, default='small')
    flavor = models.ForeignKey('IceCream', on_delete=models.CASCADE)
    toppings = models.ManyToManyField('Topping', blank=True)
    cone = models.ForeignKey('Cone', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.flavor} | {self.cone} | {self.size} | {[str(topping) for topping in list(self.toppings.all())]}"

    def get_cone_info(self):
        return {'size': str(self.size),
                'flavor': str(self.flavor),
                'toppings': [str(topping) for topping in list(self.toppings.all())],
                'cone': str(self.cone),
                'price': str(self.get_price())}

    def get_price(self):
        price = self.cone.price + sum(topping.price for topping in self.toppings.all())
        match self.size:
            case 'small':
                price += self.flavor.price * 1
            case 'medium':
                price += self.flavor.price * 2
            case 'large':
                price += self.flavor.price * 3
        return price


class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('preparing', 'Preparing'),
        ('delivering', 'Delivering'),
        ('delivered', 'Delivered'),
        ('canceled', 'Canceled'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    drone = models.ForeignKey(Drone, on_delete=models.SET_NULL, blank=True, null=True)
    cones = models.JSONField()
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order #{self.pk} - {self.status}"

    def get_order_total(self):
        total_price = Decimal('0.00')
        cone_data_list = self.cones if isinstance(self.cones, list) else [self.cones]

        for cone_data in cone_data_list:
            cone_price = Decimal(cone_data.get('price', '0.00'))
            total_price += cone_price

        return total_price

    def get_cone_info(self):
        # Check if `self.cones` is a list of dictionaries (JSON data)
        if isinstance(self.cones, list):
            return self.cones
        # If `self.cones` is a single dictionary, return it inside a list
        elif isinstance(self.cones, dict):
            return [self.cones]
        # If `self.cones` is neither, return an empty list
        else:
            return []

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cart')
    cones = models.ManyToManyField('IceCreamCone', blank=True)

    def remove_all_cones(self):
        self.cones.clear()

    def get_cones_info(self):
        return [cone.cone_to_json() for cone in self.cones.all()]

    def __str__(self):
        return f"{self.user.username}'s cart"

DroneCone/DroneAdmin/forms.py
from django import forms
from django.contrib.auth.models import User
# noinspection PyUnresolvedReferences
from DroneCustomer.models import Drone, IceCream, Topping, Cone, Markup
# noinspection PyUnresolvedReferences
from Account.models import Profile
from decimal import Decimal


class MarkupForm(forms.ModelForm):
    class Meta:
        model = Markup
        fields = ['markup_percentage']

        widgets = {
            'markup_percentage': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'})
        }

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'is_staff']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [ 'phone', 'address', 'drone_owner']

        widgets = {
            'phone': forms.TextInput(attrs={'class': 'border border-gray-400 rounded'}),
            'address': forms.TextInput(attrs={'class': 'border border-gray-400 rounded'}),
            'drone_owner': forms.CheckboxInput(attrs={'class': 'border border-gray-400 rounded'}),
        }

class CustomNumberInput(forms.NumberInput):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('attrs', {})
        kwargs['attrs'].update({'class': 'border border-gray-400 rounded text-right'})
        super().__init__(*args, **kwargs)

class DroneForm(forms.ModelForm):
    battery_level = forms.DecimalField(
        max_value=Decimal('1.0'),
        min_value=Decimal('0.0'),
        widget=CustomNumberInput(),
    )

    class Meta:
        model = Drone
        fields = [
            'owner',
            'name',
            'size',
            'drone_weight_g',
            'battery_capacity_mAh',
            'battery_voltage',
            'battery_level',
            'enabled',
            'in_flight'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'border border-gray-400 rounded'}),
            'drone_weight_g': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
            'battery_capacity_mAh': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
            'battery_voltage': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
            'enabled': forms.CheckboxInput(attrs={'class': 'border border-gray-400 rounded'}),
            'in_flight': forms.CheckboxInput(attrs={'class': 'border border-gray-400 rounded'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['owner'].queryset = User.objects.filter(profile__drone_owner=True)

class IceCreamForm(forms.ModelForm):
    class Meta:
        model = IceCream
        fields = ['flavor', 'price', 'qty']
        widgets = {
            'flavor': forms.TextInput(attrs={'class': 'border border-gray-400 rounded'}),
            'price': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
            'qty': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
        }

class BaseForm(forms.ModelForm):
    class Meta:
        widgets = {
            'name': forms.TextInput(attrs={'class': 'border border-gray-400 rounded'}),
            'price': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
            'qty': forms.NumberInput(attrs={'class': 'border border-gray-400 rounded text-right'}),
        }

class ToppingForm(BaseForm):
    class Meta:
        model = Topping
        fields = ['name', 'price', 'qty']

class ConeForm(BaseForm):
    class Meta:
        model = Cone
        fields = ['name', 'price', 'qty']

DroneCone/DroneAdmin/templates/DroneAdmin/add_drone.html
{% extends 'DroneAdmin/base.html' %}

{% block title %}{{ action_title }} Drone{% endblock %}
{% block heading %}{{ action_title }} Drone{% endblock %}

{% block content %}
    <div class="bg-white p-4 shadow bg-gray-100">
        <form method="post">
            {% csrf_token %}
            <table class="table-auto w-full">
                <tr>
                    <td class="font-semibold">Owner:</td>
                    <td>{{ form.owner }}</td>
                </tr>
                <tr>
                    <td class="font-semibold">Name:</td>
                    <td>{{ form.name }}</td>
                </tr>
                <tr>
                    <td class="font-semibold">Size:</td>
                    <td>{{ form.size }}</td>
                </tr>
                <tr>
                    <td class="font-semibold">Weight:</td>
                    <td>
                        {{ form.drone_weight_g }}
                        <small class="text-gray-500">g</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold">Battery Capacity:</td>
                    <td>
                        {{ form.battery_capacity_mAh }}
                        <small class="text-gray-500">mAh</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold">Battery Voltage:</td>
                    <td>
                        {{ form.battery_voltage }}
                        <small class="text-gray-500">v</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold">Battery Level:</td>
                    <td>
                        {{ form.battery_level }}
                        <small class="text-gray-500">% (Must be a decimal between 1.0 and 0.0)</small>
                    </td>
                </tr>
                <tr>
                    <td class="font-semibold">Drone is Enabled:</td>
                    <td>{{ form.enabled }}</td>
                </tr>
                <tr>
                    <td class="font-semibold">Drone is in-flight:</td>
                    <td>{{ form.in_flight }}</td>
                </tr>
            </table>

            <div class="mt-4 flex items-center">
                <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded-md">Save</button>
                <a href="{% url 'drone_management' %}" class="ml-2 text-gray-500">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/add_topping.html
{% extends 'DroneAdmin/base.html' %}

{% block title %}{{ action_title }} Topping{% endblock %}
{% block heading %}{{ action_title }} Topping{% endblock %}

{% block content %}
    <div class="bg-white p-4 shadow bg-gray-100">
        <form method="post">
            {% csrf_token %}

            <table class="table-auto w-full">
                <tr>
                    <td class="font-semibold">Name:</td>
                    <td>{{ form.name }}</td>
                </tr>
                <tr>
                    <td class="font-semibold">Price:</td>
                    <td>{{ form.price }}</td>
                </tr>
                <tr>
                    <td class="font-semibold">Quantity:</td>
                    <td>{{ form.qty }}</td>
                </tr>
            </table>

            <div class="mt-4 flex items-center">
                <button type="submit" class="flex bg-green-500 text-white px-4 py-2 rounded-md">Save</button>
                <a href="{% url 'inventory' %}" class="ml-2 text-gray-500">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/base.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
	{{ block.super }}
    <link rel="stylesheet" href="{% static 'DroneAdmin/style.css' %}">
{% endblock %}
{% block inner %}


<div class="flex flex-col min-h-screen">
    <div class="flex flex-grow">
        <aside class="w-1/8 p-4 min-h-screen border-r border-gray-400">
            <h2 class="text-lg font-semibold mb-4">Administration</h2>
            <ul class="space-y-2 resolute">
                <li class="{% if request.resolver_match.url_name == 'order_history' %}border-l-4 border-blue-400{% endif %}">
                    <a href="{% url 'order_history' %}">Order History</a>
                </li>
                <li class="{% if 'drone_management' in request.resolver_match.url_name %}border-l-4 border-blue-400{% endif %}">
                    <a href="{% url 'drone_management' %}">Drone Management</a>
                </li>
                <li class="{% if 'inventory' in request.resolver_match.url_name %}border-l-4 border-blue-400{% endif %}">
                    <a href="{% url 'inventory' %}">Inventory</a>
                </li>
                <li class="{% if 'user_management' in request.resolver_match.url_name %}border-l-4 border-blue-400{% endif %}">
                    <a href="{% url 'user_management' %}">User Management</a>
                </li>
                <li class="{% if 'sales' in request.resolver_match.url_name %}border-l-4 border-blue-400{% endif %}">
                    <a href="{% url 'sales' %}">Sales</a>
                </li>
            </ul>
        </aside>
        <main class="w-7/8 p-8">
            <h1 class="text-3xl font-semibold mb-4">{% block heading %}{% endblock %}</h1>
            {% block content %}{% endblock %}
        </main>
    </div>
</div>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/delete_cone.html
{% extends "DroneAdmin/base.html" %}

{% block title %}Delete Cone{% endblock %}
{% block heading %}Delete Cone{% endblock %}

{% block content %}
    <p>Are you sure you want to delete this cone type?</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'inventory' %}">Cancel</a>
        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md mt-2">Delete</button>
    </form>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/delete_ice_cream.html
{% extends "DroneAdmin/base.html" %}

{% block title %}Delete Ice Cream{% endblock %}
{% block heading %}Delete Ice Cream{% endblock %}

{% block content %}
    <p>Are you sure you want to delete this flavor?</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'inventory' %}">Cancel</a>
        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md mt-2">Delete</button>
    </form>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/delete_topping.html
{% extends "DroneAdmin/base.html" %}

{% block title %}Delete Topping{% endblock %}
{% block heading %}Delete Topping{% endblock %}

{% block content %}
    <p>Are you sure you want to delete this topping?</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'inventory' %}">Cancel</a>
        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md mt-2">Delete</button>
    </form>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/delete_user.html
{% extends "DroneAdmin/base.html" %}

{% block title %}Delete User{% endblock %}
{% block heading %}Delete User{% endblock %}

{% block content %}
    <p>Are you sure you want to delete this user?</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'user_management' %}">Cancel</a>
        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded-md mt-2">Delete</button>
    </form>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/drone_management.html
{% extends 'DroneAdmin/base.html' %}

{% block title %}Drone Management{% endblock %}
{% block heading %}Drone Management{% endblock %}

{% block content %}
    <table class="min-w-full divide-y divide-gray-200 shadow bg-gray-100">
        <thead>
            <tr>
                <th class="px-6 py-3"></th>
                <th class="px-6 py-3">Name</th>
                <th class="px-6 py-3">Owner</th>
                <th class="px-6 py-3">Size</th>
                <th class="px-6 py-3">Weight (g)</th>
                <th class="px-6 py-3">Battery Capacity (mAh)</th>
                <th class="px-6 py-3">Battery Voltage (V)</th>
                <th class="px-6 py-3">Battery Level (%)</th>
                <th class="px-6 py-3">Status</th>
                <th class="px-6 py-3">Hours Worked</th>
                <th class="px-6 py-3">Dollar Revenue</th>
                <th class="px-6 py-3">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for drone in drones %}
                <tr>
                    <td class="px-6 py-3 whitespace-nowrap">
                        {{ forloop.counter }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.name }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.owner }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.get_size_display }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.drone_weight_g }} g
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.battery_capacity_mAh }} mAh
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.battery_voltage }} v
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.battery_level }}%
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.get_drone_status }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.hours_worked }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {{ drone.dollar_revenue }}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap">
                        <button onclick="window.location.href='{% url 'add_drone' drone.id %}'" class="bg-blue-500 text-white px-4 py-2 rounded-md">Edit</button>
                        <button onclick="window.location.href='{% url 'delete_drone' drone.id %}'" class="bg-red-500 text-white px-4 py-2 rounded-md">Delete</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <button onclick="window.location.href='{% url 'add_drone' %}'" class="block bg-green-500 text-white px-4 py-2 rounded-md my-2">Add</button>
{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/edit_markup.html
{% extends 'DroneAdmin/base.html' %}

{% block title %}Edit Markup{% endblock %}
{% block heading %}Edit Markup{% endblock %}

{% block content %}
    <div class="bg-white p-4 shadow bg-gray-100">
        <form method="post">
            {% csrf_token %}
            <table class="table-auto w-full bg-gray-100">
                <tr>
                    <td class="font-semibold">Markup Percentage: </td>
                    <td>
                        {{ form.markup_percentage }}
                        <small class="text-gray-500">%</small>
                    </td>
                </tr>
            </table>
            <div class="mt-4 flex items-center">
                <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded-md">Save</button>
                <a href="{% url 'sales' %}" class="ml-2 text-gray-500">Cancel</a>
            </div>
        </form>
    </div>

{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/edit_user.html
{% extends 'DroneAdmin/base.html' %}

{% block title %}{{ action_title }} User{% endblock %}
{% block heading %}{{ action_title }} User{% endblock %}

{% block content %}
    <div class="bg-white p-4 shadow bg-gray-100">
        <form method="post">
            {% csrf_token %}
            <table class="table-auto w-full">
                <tr>
                    <td class="font-semibold text-gray-700">Username:</td>
                    <td>{{ user_form.username }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Email:</td>
                    <td>{{ user_form.email }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Admin:</td>
                    <td>{{ user_form.is_staff }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Phone:</td>
                    <td>{{ profile_form.phone }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Address:</td>
                    <td>{{ profile_form.address }}</td>
                </tr>
                <tr>
                    <td class="font-semibold text-gray-700">Drone owner:</td>
                    <td>{{ profile_form.drone_owner }}</td>
                </tr>
            </table>
            <div class="mt-4 flex items-center">
                <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded-md">Save</button>
                <a href="{% url 'user_management' %}" class="ml-2 text-gray-500">Cancel</a>
            </div>
        </form>
    </div>

{% endblock %}

DroneCone/DroneAdmin/templates/DroneAdmin/order_history.html
{% extends 'DroneAdmin/base.html' %}

{% block title %}Orders{% endblock %}
{% block heading %}Orders{% endblock %}

{% block content %}
    <table class="min-w-full divide-y divide-gray-200 shadow bg-gray-100">
        <thead>
            <tr>
                <th class="px-6 py-3">Order ID</th>
                <th class="px-6 py-3">User</th>
                <th class="px-6 py-3">Ice Cream Cones</th>
                <th class="px-6 py-3">Status</th>
                <th class="px-6 py-3">Drone</th>
                <th class="px-6 py-3">Created At</th>
                <th class="px-6 py-3">Updated At</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td class="px-6 py-3 whitespace-nowrap text-center">{{ order.pk }}</td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">{{ order.user.username }}</td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">
                        {% for cone_details in order.cones %}
                            <p><strong>Size:</strong> {{ cone_details.size }}</p>
                            <p><strong>Flavor:</strong> {{ cone_details.flavor.flavor }}</p>
                            <p><strong>Flavor Price:</strong> ${{ cone_details.flavor.price }}</p>
                            <p><strong>Toppings:</strong></p>
                            <ul>
                                {% for topping in cone_details.toppings %}
                                    <li>{{ topping.name }} - ${{ topping.price }}</li>
                                {% endfor %}
                            </ul>
                            <p><strong>Cone:</strong> {{ cone_details.cone.name }}</p>
                            <p><strong>Cone Price:</strong> ${{ cone_details.cone.price }}</p>

                            <p><strong>Total Price:</strong> ${{ cone_details.price }}</p>
                            <hr>
                        {% endfor %}
                    </td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">{{ order.get_status_display }}</td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">{{ order.drone }}</td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">{{ order.created_at }}</td>
                    <td class="px-6 py-3 whitespace-nowrap text-center">{{ order.updated_at }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}